### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by ko-suke24** [ko-suke24/chat-space#11]
# IPアドレス
18.182.208.34

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①サイドバーの「グループ名」「最新メッセージ」の下線を消しましょう

②送信したメッセージの「ユーザー名」「送信日時」「メッセージ」が、見本と同じ表示になるようにしましょう

<現在>
<img width="730" alt="スクリーンショット 2020-05-15 20 54 41" src="https://user-images.githubusercontent.com/49669977/82047937-a56d2d80-96ee-11ea-957a-b6c8e5934fa9.png">


<見本>
<img width="560" alt="スクリーンショット 2020-05-15 20 57 37" src="https://user-images.githubusercontent.com/49669977/82047986-bc138480-96ee-11ea-821b-443bb0c38294.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ko-suke24** [comment]
修正しました！

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項はしっかり修正が確認できました！
新たに以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①グループ編集画面とグループ新規作成画面の削除ボタンの位置を見本通りにしましょう**
<img width="656" alt="スクリーンショット 2020-05-16 16 54 18" src="https://user-images.githubusercontent.com/49669977/82114191-26333480-9796-11ea-8fc6-907334cc2a39.png">


**②メッセージ送信ボックスの、「type a message」の位置を見本通りにしましょう**
<img width="477" alt="スクリーンショット 2020-05-16 16 55 03" src="https://user-images.githubusercontent.com/49669977/82114205-3e0ab880-9796-11ea-914f-ad92301d3873.png">


**③グループ編集画面にて、「更新」ボタンを押した後に、
　トップページではなく、もともといたグループに飛ぶようにしましょう**

修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ko-suke24** [comment]
修正しました！

**Comment by mo1015** [comment]
再提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by ko-suke24** [comment]
ありがとうございました！
